# Miniprot divergence threhold determination

Let's look at some of the log files between mmseqs and miniprot to see if we can infer good threholds model of the latter based on the former

In [5]:
from pathlib import Path
import re
import sys
from dataclasses import dataclass, field

from Bio import SeqIO
import polars as pl
from intervaltree import Interval, IntervalTree

In [6]:
data_dir = Path("/home/yjkbertrand/Documents/projects/nextpyper_simulation/miniprot_divergence/data/batrachium")
mmseqs_dir = data_dir / "mmseqs_logs"
miniprot_dir = data_dir / "miniprot_logs"

The good thing is that the mmseqs logs are eqasy to parse, they are structured already

In [7]:
pl.read_csv(mmseqs_dir / "BA_28_1.log", separator="\t")

shape: (13_256, 12)
┌────────────────────┬────────────┬───────┬────────┬───┬─────────┬───────────┬──────────┬──────────┐
│ query              ┆ theader    ┆ cis   ┆ nident ┆ … ┆ adj_cov ┆ cov       ┆ idt      ┆ eff_cov  │
│ ---                ┆ ---        ┆ ---   ┆ ---    ┆   ┆ ---     ┆ ---       ┆ ---      ┆ ---      │
│ str                ┆ str        ┆ bool  ┆ i64    ┆   ┆ i64     ┆ f64       ┆ f64      ┆ f64      │
╞════════════════════╪════════════╪═══════╪════════╪═══╪═════════╪═══════════╪══════════╪══════════╡
│ BA_28_1|BA_28_1-61 ┆ probe_6152 ┆ true  ┆ 380    ┆ … ┆ 386     ┆ 0.674825  ┆ 0.957179 ┆ 0.645928 │
│ 52_EDGE_66_l…      ┆            ┆       ┆        ┆   ┆         ┆           ┆          ┆          │
│ BA_28_1|K22_14_1-5 ┆ probe_5973 ┆ false ┆ 205    ┆ … ┆ 207     ┆ 0.485915  ┆ 0.966981 ┆ 0.469871 │
│ 973_EDGE_14_…      ┆            ┆       ┆        ┆   ┆         ┆           ┆          ┆          │
│ BA_28_1|IT_07_1-61 ┆ probe_6152 ┆ true  ┆ 103    ┆ … ┆ 106     ┆ 0.185315  ┆ 0.944954 ┆ 0.175114 │
│ 52_EDGE_1209…      ┆            ┆       ┆        ┆   ┆         ┆           ┆          ┆          │
│ BA_28_1|SP_04_4-48 ┆ probe_4816 ┆ true  ┆ 91     ┆ … ┆ 93      ┆ 0.156303  ┆ 0.968085 ┆ 0.151314 │
│ 16_EDGE_733_…      ┆            ┆       ┆        ┆   ┆         ┆           ┆          ┆          │
│ BA_28_1|BA_28_1-67 ┆ probe_672  ┆ true  ┆ 472    ┆ … ┆ 472     ┆ 0.669504  ┆ 0.882243 ┆ 0.590665 │
│ 2_EDGE_2051_…      ┆            ┆       ┆        ┆   ┆         ┆           ┆          ┆          │
│ …                  ┆ …          ┆ …     ┆ …      ┆ … ┆ …       ┆ …         ┆ …        ┆ …        │
│ BA_28_1|SW_13_1-75 ┆ probe_7581 ┆ true  ┆ 309    ┆ … ┆ 334     ┆ 0.536116  ┆ 0.895652 ┆ 0.480173 │
│ 81_EDGE_1168…      ┆            ┆       ┆        ┆   ┆         ┆           ┆          ┆          │
│ BA_28_1|K22_16_1-9 ┆ probe_9449 ┆ true  ┆ 103    ┆ … ┆ 102     ┆ 0.284916  ┆ 0.990385 ┆ 0.282177 │
│ 449_EDGE_258…      ┆            ┆       ┆        ┆   ┆         ┆           ┆          ┆          │
│ BA_28_1|BA_28_1-73 ┆ probe_7338 ┆ true  ┆ 105    ┆ … ┆ 104     ┆ 0.197719  ┆ 0.929204 ┆ 0.183721 │
│ 38_EDGE_131_…      ┆            ┆       ┆        ┆   ┆         ┆           ┆          ┆          │
│ BA_28_1|BA_28_1-91 ┆ probe_9132 ┆ true  ┆ 71     ┆ … ┆ 75      ┆ 0.1953125 ┆ 0.8875   ┆ 0.17334  │
│ 32_EDGE_2832…      ┆            ┆       ┆        ┆   ┆         ┆           ┆          ┆          │
│ BA_28_1|K15_12_01- ┆ probe_9099 ┆ true  ┆ 587    ┆ … ┆ 617     ┆ 0.671382  ┆ 0.936204 ┆ 0.628551 │
│ 9099_EDGE_24…      ┆            ┆       ┆        ┆   ┆         ┆           ┆          ┆          │
└────────────────────┴────────────┴───────┴────────┴───┴─────────┴───────────┴──────────┴──────────┘

In [8]:
mmseqs_tables = {file.stem:pl.read_csv(file, separator="\t") for file in sorted(mmseqs_dir.glob("*.log"))}

In [9]:
len(mmseqs_tables)

232

In [10]:
mmseqs_tables["B16_001_01"]

shape: (14_642, 12)
┌──────────────────────┬────────────┬──────┬────────┬───┬─────────┬──────────┬──────────┬──────────┐
│ query                ┆ theader    ┆ cis  ┆ nident ┆ … ┆ adj_cov ┆ cov      ┆ idt      ┆ eff_cov  │
│ ---                  ┆ ---        ┆ ---  ┆ ---    ┆   ┆ ---     ┆ ---      ┆ ---      ┆ ---      │
│ str                  ┆ str        ┆ bool ┆ i64    ┆   ┆ i64     ┆ f64      ┆ f64      ┆ f64      │
╞══════════════════════╪════════════╪══════╪════════╪═══╪═════════╪══════════╪══════════╪══════════╡
│ B16_001_01|K17_49_1- ┆ probe_7680 ┆ true ┆ 94     ┆ … ┆ 99      ┆ 0.168081 ┆ 0.94     ┆ 0.157997 │
│ 7680_EDGE_…          ┆            ┆      ┆        ┆   ┆         ┆          ┆          ┆          │
│ B16_001_01|B16_001_0 ┆ probe_6955 ┆ true ┆ 362    ┆ … ┆ 365     ┆ 0.793478 ┆ 0.975741 ┆ 0.774229 │
│ 1-6955_EDG…          ┆            ┆      ┆        ┆   ┆         ┆          ┆          ┆          │
│ B16_001_01|B16_001_0 ┆ probe_9988 ┆ true ┆ 259    ┆ … ┆ 264     ┆ 0.506718 ┆ 0.938406 ┆ 0.475507 │
│ 1-9988_EDG…          ┆            ┆      ┆        ┆   ┆         ┆          ┆          ┆          │
│ B16_001_01|B16_001_0 ┆ probe_9344 ┆ true ┆ 436    ┆ … ┆ 448     ┆ 0.995556 ┆ 0.937634 ┆ 0.933467 │
│ 1-9344_EDG…          ┆            ┆      ┆        ┆   ┆         ┆          ┆          ┆          │
│ B16_001_01|B16_001_0 ┆ probe_9087 ┆ true ┆ 99     ┆ … ┆ 98      ┆ 0.16092  ┆ 0.980198 ┆ 0.157733 │
│ 1-9087_EDG…          ┆            ┆      ┆        ┆   ┆         ┆          ┆          ┆          │
│ …                    ┆ …          ┆ …    ┆ …      ┆ … ┆ …       ┆ …        ┆ …        ┆ …        │
│ B16_001_01|SW_13_1-2 ┆ probe_2100 ┆ true ┆ 192    ┆ … ┆ 191     ┆ 0.415217 ┆ 0.984615 ┆ 0.408829 │
│ 100_EDGE_7…          ┆            ┆      ┆        ┆   ┆         ┆          ┆          ┆          │
│ B16_001_01|K22_16_1- ┆ probe_1568 ┆ true ┆ 137    ┆ … ┆ 141     ┆ 0.148577 ┆ 0.925676 ┆ 0.137535 │
│ 1568_EDGE_…          ┆            ┆      ┆        ┆   ┆         ┆          ┆          ┆          │
│ B16_001_01|IT_44_06- ┆ probe_3393 ┆ true ┆ 329    ┆ … ┆ 337     ┆ 0.676707 ┆ 0.911357 ┆ 0.616722 │
│ 3393_EDGE_…          ┆            ┆      ┆        ┆   ┆         ┆          ┆          ┆          │
│ B16_001_01|B16_001_0 ┆ probe_561  ┆ true ┆ 377    ┆ … ┆ 374     ┆ 0.532764 ┆ 0.964194 ┆ 0.513688 │
│ 1-561_EDGE…          ┆            ┆      ┆        ┆   ┆         ┆          ┆          ┆          │
│ B16_001_01|B16_001_0 ┆ probe_6091 ┆ true ┆ 376    ┆ … ┆ 383     ┆ 0.569094 ┆ 0.954315 ┆ 0.543094 │
│ 1-6091_EDG…          ┆            ┆      ┆        ┆   ┆         ┆          ┆          ┆          │
└──────────────────────┴────────────┴──────┴────────┴───┴─────────┴──────────┴──────────┴──────────┘

In [143]:
import plotly.express as px
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt
df = mmseqs_tables["SP_23_3"].filter(pl.col('cov') > 0.8).select("idt")
nbins = len(np.histogram_bin_edges(df, bins='auto', range=(0.6, 1)))
print(nbins)
fig = px.histogram(df, x="idt", nbins=nbins)
fig.show()

f = fig.full_figure_for_development(warn=False)
xbins = f.data[0].xbins

plotbins = list(np.arange(start=xbins['start'], stop=xbins['end']+xbins['size'], step=xbins['size']))
counts, bins = np.histogram(df, bins=plotbins)
# print(counts, bins)
def gaussian(x, mu, sigma, a):
    return a*np.exp(-(x-mu)**2/2/sigma**2)
def bimodal(x,mu1,sigma1,A1,mu2,sigma2,A2):
    return gaussian(x,mu1,sigma1,A1)+gaussian(x,mu2,sigma2,A2)

gau_params, gau_covariance = curve_fit(gaussian, bins[:-1], counts)
bi_params, bi_covariance=curve_fit(bimodal, bins[:-1], counts)
a_fit, b_fit, c_fit = gau_params
print(f"Gaussian fit: {a_fit}, {b_fit}, {c_fit}")
a0_fit, b0_fit, c0_fit, a1_fit, b1_fit, c1_fit = bi_params
print(f"Bimodal fit: {a0_fit}, {b0_fit}, {c0_fit}, {a1_fit}, {b1_fit}, {c1_fit}")
# plt.scatter(bins[:-1], counts, label='Data')
# x_fine = np.linspace(xbins['start'], 1)
# plt.plot(x_fine, gaussian(x_fine, a_fit, b_fit, c_fit), 'r-', label='gaussian fit')
# plt.plot(x_fine, bimodal(x_fine, a0_fit, b0_fit, c0_fit, a1_fit, b1_fit, c1_fit), 'b-', label='bimodal fit')
# plt.legend()
# plt.show()
from sklearn.mixture import GaussianMixture
X = np.array([np.array([x, y]) for x, y in zip(bins[:-1], counts) if y>10])
gm_2 = GaussianMixture(n_components=2, random_state=0).fit(X )
print(f"bic 2 is {gm_2.bic(X)}")
print(f'mu1={gm_2.means_[0]},) mu2={gm_2.means_[1]}')
print(f'sigma1={np.sqrt(gm_2.covariances_[0])}, sigma2={np.sqrt(gm_2.covariances_[1])}')
print(f'w1={gm_2.weights_[0]}, w2={gm_2.weights_[1]}')
print(f'n1={int(nbins * gm_2.weights_[0])} n2={int(nbins * gm_2.weights_[1])}')
gm_1 = GaussianMixture(n_components=1, random_state=0).fit(X)
print(f"bic 1 is {gm_1.bic(X)}")
print(f'mu1={gm_1.means_[0]}')
print(f'sigma1={np.sqrt(gm_1.covariances_[0])}')
print(f'w1={gm_1.weights_[0]}')
print(f'n1={int(nbins * gm_1.weights_[0])}')
# plt.scatter(bins[:-1], counts, label='Data')
# logprob = gm.score_samples(list(zip(bins[:-1], counts)))
# pdf = np.exp(logprob)
# plt.plot(list(zip(bins[:-1], counts)), pdf, '-r')
# fig = px.scatter(df, x="idt", y='cov')

73

Gaussian fit: 0.9501051807399288, -0.025246654049604262, 207.84259783794442
Bimodal fit: 0.9501052325391931, 0.025246691912075424, 207.84244788729055, 1.604525984268753, 0.028021914380083696, 202.9505314120937
bic 2 is 187.66815023179524
mu1=[  0.94774582 198.03036223],) mu2=[ 0.93060945 78.61791197]
sigma1=[[1.04075126e-02 7.26251541e-01]
 [7.26251541e-01 5.47167842e+01]], sigma2=[[4.18672622e-02 8.37326534e-01]
 [8.37326534e-01 4.73765167e+01]]
w1=0.28792716300946763, w2=0.7120728369905324
n1=21 n2=51
bic 1 is 187.66027431620589
mu1=[  0.93554348 113.        ]
sigma1=[[3.66000455e-02 1.03472324e+00]
 [1.03472324e+00 7.33745602e+01]]
w1=1.0
n1=73

/tmp/ipykernel_4141677/442748542.py:23: OptimizeWarning:

Covariance of the parameters could not be estimated

In [146]:
#Make a grid search for the best combination of number of gaussian distributions and covariance type
from sklearn.mixture import GaussianMixture
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import make_blobs

#X, _ = make_blobs(n_samples=10_000, centers=3)

param_grid = {
    'n_components': range(1, 7),
    'covariance_type': ['spherical', 'tied', 'diag', 'full']
}

def bic_scorer(fitted_gmm, X):
    return -fitted_gmm.bic(X)  # return -bic as higher is better for GridSearchCV

gs = GridSearchCV(GaussianMixture(), param_grid=param_grid, scoring=bic_scorer)
gs.fit(X)
gs.best_score_, gs.best_params_

{'scoring': <function bic_scorer at 0x7cf4e6f863e0>, 'estimator': GaussianMixture(), 'n_jobs': None, 'refit': True, 'cv': None, 'verbose': 0, 'pre_dispatch': '2*n_jobs', 'error_score': nan, 'return_train_score': False, 'param_grid': {'n_components': range(1, 7)}, 'multimetric_': False, 'best_index_': np.int64(0), 'best_score_': np.float64(-67.46687901167499), 'best_params_': {'n_components': 1}, 'best_estimator_': GaussianMixture(), 'refit_time_': 0.0018267631530761719, 'scorer_': <function bic_scorer at 0x7cf4e6f863e0>, 'cv_results_': {'mean_fit_time': array([0.00221815, 0.00642219, 0.00601931, 0.0078752 , 0.00604362,
       0.00390067]), 'std_fit_time': array([0.00035986, 0.00289878, 0.00341829, 0.00663253, 0.0020367 ,
       0.00020901]), 'mean_score_time': array([0.00037489, 0.00040421, 0.000386  , 0.00037932, 0.00045538,
       0.00048985]), 'std_score_time': array([4.35234014e-05, 4.57432249e-05, 6.04043716e-05, 3.78808034e-05,
       7.84754309e-05, 6.84151823e-05]), 'param_n_components': masked_array(data=[1, 2, 3, 4, 5, 6],
             mask=[False, False, False, False, False, False],
       fill_value=999999), 'params': [{'n_components': 1}, {'n_components': 2}, {'n_components': 3}, {'n_components': 4}, {'n_components': 5}, {'n_components': 6}], 'split0_test_score': array([ -85.69246291, -141.60208971,  -99.92511808, -173.37997484,
       -183.03660407, -434.38891095]), 'split1_test_score': array([ -39.73541554,  -57.1247404 ,  -95.84971592,  -96.08262039,
       -112.52078639, -122.17741387]), 'split2_test_score': array([ -43.39093347,  -57.18882957,  -87.65725038, -134.73841483,
       -189.62977642, -675.53380674]), 'split3_test_score': array([ -45.92934845,  -62.75720463,  -80.50600244, -100.70767423,
       -208.41512235, -331.5631623 ]), 'split4_test_score': array([-122.58623468,  -77.42445906, -141.23677526, -159.11441146,
       -239.40064379, -222.04569013]), 'mean_test_score': array([ -67.46687901,  -79.21946468, -101.03497242, -132.80461915,
       -186.60058661, -357.1417968 ]), 'std_test_score': array([ 32.19585601,  32.06039825,  21.18823102,  30.72791334,
        41.88893594, 190.50148266]), 'rank_test_score': array([1, 2, 3, 4, 5, 6], dtype=int32)}, 'n_splits_': 5}

(np.float64(-67.46687901167499), {'n_components': 1})

In [108]:
df = mmseqs_tables["SP_24_1"].filter(pl.col('cov') > 0.5)
fig = px.histogram(df, x="idt", nbins=50)
fig.show()

In [106]:
keys = ["SE_14_1","SE_17_1","SE_20_1","SE_24_1"]
dfs = [mmseqs_tables[key].filter(pl.col('cov') > 0.5).with_columns(pl.lit(key).alias("acc")) for key in keys ]
new_df = pl.concat(dfs)
#new_df
fig = px.histogram(new_df, x="idt", nbins=500,color="acc")
fig.show()

In [45]:
df = mmseqs_tables["SP_24_1"]
fig = px.scatter(df, x="idt", y='cov')
fig.show()

In [148]:
mmseqs_dir = Path("/home/yjkbertrand/Documents/projects/nextpyper_simulation/miniprot_divergence/scfs_filtering")
mmseqs_tables_hier = {file.stem:pl.read_csv(file, separator="\t") for file in sorted(mmseqs_dir.glob("*.log"))}

In [172]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go
dfs = [mmseqs_tables_hier[key].filter(pl.col('cov') > 0.1).with_columns(pl.lit(key).alias("acc")).select("idt") for key in mmseqs_tables_hier.keys() ]
total_rows = len(dfs)
total_cols = 1
fig = make_subplots(rows=total_rows, cols=total_cols, shared_xaxes=True, vertical_spacing=0.02,subplot_titles=list(mmseqs_tables_hier.keys()),
                    shared_yaxes=True)

fig.update_layout(height=2000, width=1500, title_text=f"Similarity histograms",
    template="plotly")
for i, df in enumerate(dfs):
    fig.add_trace(go.Histogram(x=df["idt"],nbinsx=100),row=i+1,col=1)
    #fig.add_trace(go.Scatter(x=df["idt"],y=df['cov']))
# new_df = pl.concat(dfs)
# #new_df
# fig = px.histogram(new_df, x="idt", nbins=500,color="acc")
fig.show()

In [171]:
from polars import DataFrame
def get_histogram_data(df:DataFrame, min_range:float=0.5) ->tuple[list, list]:
    """"
    Automatically infer the best number of bins in the histogram.
    Return x, y coordinates with y the height of the bar and y the central value of the bar.
    """
    nbins = len(np.histogram_bin_edges(df, bins='auto', range=(min_range, 1)))
    tmp_fig = px.histogram(df, x="idt", nbins=nbins)
    f = tmp_fig.full_figure_for_development(warn=False)
    xbins = f.data[0].xbins
    plotbins = list(np.arange(start=xbins['start'], stop=xbins['end']+xbins['size'], step=xbins['size']))
    counts, bins = np.histogram(df, bins=plotbins)
    return (bins, counts)
param_grid = {
    'n_components': range(1, 7),
    'covariance_type': ['spherical', 'tied', 'diag', 'full']
}
histogram_data = [get_histogram_data(df) for df in dfs]
Xs = [np.array([np.array([x, y]) for x, y in zip(item[0][:-1], item[1]) if y>10]) for item in histogram_data]
#Xs = [np.array([np.array([x, y]) for x, y in zip(item[0][:-1], item[1])]) for item in histogram_data]
for idx, X in enumerate(Xs):
    print(list(mmseqs_tables_hier.keys())[idx])
    gs = GridSearchCV(GaussianMixture(), param_grid=param_grid, scoring=bic_scorer)
    gs.fit(X)
    print(gs.best_score_, gs.best_params_)

Andryala_integrifolia_ERR7618428
-24.910008832517583 {'covariance_type': 'diag', 'n_components': 1}
Cichorium_intybus_ERR5033750
-23.818505410858307 {'covariance_type': 'diag', 'n_components': 1}
Echinops_strigosus_ERR5033325
-10.717710171342965 {'covariance_type': 'diag', 'n_components': 1}
Lactuca_floridana_ERR5033752
-28.470916426158276 {'covariance_type': 'diag', 'n_components': 1}
Pilosella_piloselloides_ERR7618430
-19.724936902708713 {'covariance_type': 'diag', 'n_components': 1}

In [178]:
mmseqs_dir = Path("/home/yjkbertrand/Documents/projects/nextpyper_simulation/miniprot_divergence/more_divergence/my50_cov100")
mmseqs_tables_hier = {file.stem:pl.read_csv(file, separator="\t") for file in sorted(mmseqs_dir.glob("*Deca*.log"))}
from plotly.subplots import make_subplots
import plotly.graph_objects as go
dfs = [mmseqs_tables_hier[key].filter(pl.col('cov') > 0.1).with_columns(pl.lit(key).alias("acc")).select("idt") for key in mmseqs_tables_hier.keys() ]
total_rows = len(dfs)
total_cols = 1
fig = make_subplots(rows=total_rows, cols=total_cols, shared_xaxes=True, vertical_spacing=0.02,subplot_titles=list(mmseqs_tables_hier.keys()),
                    shared_yaxes=True)

fig.update_layout(height=2000, width=1500, title_text=f"Similarity histograms",
    template="plotly")
for i, df in enumerate(dfs):
    fig.add_trace(go.Histogram(x=df["idt"],nbinsx=50),row=i+1,col=1)

fig.show()

In [180]:
import numpy as np
import plotly.express as px
import polars as pl
from polars import DataFrame
from scipy.optimize import curve_fit

def gaussian(x, mu, sigma, a):
    """Defines a classical Gaussian distribution."""
    return a*np.exp(-(x-mu)**2/2/sigma**2)

def get_histogram_data(df:DataFrame, mmseqs_idt_threshold:float) ->tuple[list, list]:
    """"
    Automatically infer the best number of bins in the histogram.
    Return x, y coordinates with y the height of the bar and y the central value of the bar.
    """
    nbins = len(np.histogram_bin_edges(df, bins='auto', range=(mmseqs_idt_threshold, 1)))
    tmp_fig = px.histogram(df, x="idt", nbins=nbins)
    f = tmp_fig.full_figure_for_development(warn=False)
    xbins = f.data[0].xbins
    plotbins = list(np.arange(start=xbins['start'], stop=xbins['end']+xbins['size'], step=xbins['size']))
    counts, bins = np.histogram(df, bins=plotbins)
    return (bins, counts)

def find_sim_threshold_per_acc(mmseqs_log:Path, mmseqs_idt_threshold:float=0.6, min_cov:float=0.5, flattening_value:float=0.1)->float:
    """
    Given a similarity log computed by mmseqs2, fit a Gaussian distribution to the distribution of similarity values (histogram).
    Compute the mean and standard deviation of the Gaussian distribution.

    :param mmseqs_log: the path to the mmseqs2 log file.
    :param mmseqs_idt_threshold: the mmseqs2 similarity threshold.
    :param min_cov: the minimum scaffold-probe coverage.
    :param flattening_value: bins that are lower than the largest bin multiplied by the flattening_value are removed before the Gaussian curve fitting.
    :return: the lower value at 2 standard deviations from the mean that should encompass 95% of the data.
    """
    mmseqs_tables = pl.read_csv(mmseqs_log, separator="\t")
    df = mmseqs_tables.filter(pl.col('cov') > min_cov).select("idt")
    bins, counts = get_histogram_data(df, mmseqs_idt_threshold)
    min_count = max(counts) * flattening_value
    filtered_bins, filtered_counts = zip(* [(x, y) for x, y in zip(bins[:-1], counts) if y>=min_count])
    gau_params, gau_covariance = curve_fit(gaussian, filtered_bins, filtered_counts)
    mu, sigma, _ = gau_params
    print(f"Gaussian fit: {mu}, {sigma}")
    return mu - 2*abs(sigma)

print(find_sim_threshold_per_acc(Path('/home/yjkbertrand/Documents/projects/nextpyper_simulation/miniprot_divergence/data/batrachium/mmseqs_logs/AT_01_1.log')))

Gaussian fit: 0.9450421961031129, -0.027372721716440625
0.8902967526702317

Now we need to make a parser for the miniprot log files

In [12]:
miniprot_pat = r"cds\s\[Cds\(self\.mRNA_start=(?P<qstart>\d+),self\.mRNA_end=(?P<qend>\d+),self\.probe_start=(?P<tstart>\d+),self\.probe_end=(?P<tend>\d+),self\.global_identity=(?P<idt>[\d\.]+),strand=(?P<strand>-?1),\scontig=(?P<query>.*?), global_score=(?P<score>\d+)\)\]"
pat = re.compile(miniprot_pat)

In [13]:
@dataclass
class miniprotHit:
    qstart: int
    qend: int
    tstart: int
    tend: int
    idt: float
    strand: int
    query: str
    score: int
    probe: str = field(init=False)

    @classmethod
    def from_line(cls, line):
        match = pat.search(line)
        if match:
            return cls(**match.groupdict())
        else:
            raise ValueError("Line does not match expected format")
        
    def __post_init__(self):
        self.qstart = int(self.qstart)
        self.qend = int(self.qend)
        self.tstart = int(self.tstart)
        self.tend = int(self.tend)
        self.idt = float(self.idt)
        self.strand = int(self.strand)
        self.score = int(self.score)
        self.probe = re.search(r"-(.*?)_", self.query).group(1)


log = miniprot_dir / "1766.log"
with open(log) as file:
    hits = [miniprotHit.from_line(line) for line in file if line.startswith("cds") and len(line) >= 20]

In [14]:
from collections import defaultdict
miniprot_hits = defaultdict(list)
for logfile in sorted(miniprot_dir.glob("*.log")):
    with open(logfile) as file:
        for line in file:
            if line.startswith("cds") and len(line) >= 20:
                miniprot_hits[logfile.stem].append(miniprotHit.from_line(line))

In [15]:
17*6

102

In [16]:
miniprot_hits["1766"]

[miniprotHit(qstart=286, qend=2939, tstart=0, tend=430, idt=0.9206, strand=1, query='AT_01_1|AT_01_1-1766_EDGE_1739_length_3329_cov_112.0481:2:1:373008', score=2074, probe='1766'),
 miniprotHit(qstart=317, qend=2972, tstart=0, tend=430, idt=0.9274, strand=1, query='AT_01_1|AT_01_1-1766_EDGE_1739_length_3225_cov_130.5957:1:1:421171', score=2069, probe='1766'),
 miniprotHit(qstart=317, qend=1601, tstart=0, tend=280, idt=0.7936, strand=1, query='AT_01_1|AT_01_1-1766_EDGE_1738_length_1978_cov_120.5905:1:2:238528', score=1052, probe='1766'),
 miniprotHit(qstart=296, qend=611, tstart=430, tend=518, idt=0.764, strand=1, query='AT_01_1|AT_01_1-1766_EDGE_1423_length_975_cov_33.4544:1:1:32618', score=296, probe='1766'),
 miniprotHit(qstart=291, qend=642, tstart=430, tend=518, idt=0.7525, strand=1, query='AT_01_1|AT_01_1-1766_EDGE_2057_length_853_cov_15.2673:1:1:13023', score=378, probe='1766'),
 miniprotHit(qstart=128, qend=2779, tstart=0, tend=430, idt=0.9206, strand=1, query='AT_02_1|AT_02_1-1766_EDGE_1496_length_3099_cov_123.645:1:10:383176', score=2084, probe='1766'),
 miniprotHit(qstart=206, qend=2772, tstart=0, tend=430, idt=0.9206, strand=1, query='AT_02_1|AT_02_1-1766_EDGE_1496_length_3092_cov_126.4301:1:3:390922', score=2077, probe='1766'),
 miniprotHit(qstart=0, qend=2573, tstart=8, tend=430, idt=0.9169, strand=1, query='AT_02_1|AT_02_1-1766_EDGE_1496_length_2893_cov_133.2147:1:5:385390', score=2033, probe='1766'),
 miniprotHit(qstart=183, qend=2328, tstart=11, tend=430, idt=0.9372, strand=1, query='AT_02_1|IT_07_1-1766_EDGE_569_length_2648_cov_141.213:1:3:373932', score=2055, probe='1766'),
 miniprotHit(qstart=179, qend=2327, tstart=11, tend=430, idt=0.9093, strand=1, query='AT_02_1|IT_07_1-1766_EDGE_569_length_2647_cov_136.6162:1:10:361623', score=1994, probe='1766'),
 miniprotHit(qstart=368, qend=1208, tstart=281, tend=430, idt=0.9, strand=1, query='AT_02_1|AT_02_1-1766_EDGE_1496_length_1660_cov_95.7657:2:10:158971', score=705, probe='1766'),
 miniprotHit(qstart=361, qend=675, tstart=430, tend=518, idt=0.7865, strand=1, query='AT_02_1|K22_16_1-1766_EDGE_1747_length_1006_cov_54.0179:1:7:54342', score=315, probe='1766'),
 miniprotHit(qstart=374, qend=694, tstart=430, tend=518, idt=0.9033, strand=1, query='AT_02_1|K22_14_1-1766_EDGE_1088_length_960_cov_49.4208:1:8:47444', score=388, probe='1766'),
 miniprotHit(qstart=375, qend=689, tstart=430, tend=518, idt=0.6865, strand=1, query='AT_02_1|K22_14_1-1766_EDGE_1088_length_953_cov_57.8332:1:2:55115', score=302, probe='1766'),
 miniprotHit(qstart=357, qend=2501, tstart=11, tend=430, idt=0.9667, strand=1, query='AT_09_1|AT_02_1-1766_EDGE_1496_length_2828_cov_97.0636:1:3:274496', score=2071, probe='1766'),
 miniprotHit(qstart=135, qend=1691, tstart=11, tend=363, idt=0.9433, strand=1, query='AT_09_1|AT_02_1-1766_EDGE_1496_length_1934_cov_124.3475:2:1:240488', score=1753, probe='1766'),
 miniprotHit(qstart=358, qend=1199, tstart=281, tend=430, idt=0.9062, strand=1, query='AT_09_1|K17_23_1-1766_EDGE_375_length_1525_cov_63.9233:1:2:97483', score=710, probe='1766'),
 miniprotHit(qstart=330, qend=650, tstart=430, tend=518, idt=0.9033, strand=1, query='AT_09_1|AT_09_1-1766_EDGE_3202_length_947_cov_65.7339:1:1:62250', score=388, probe='1766'),
 miniprotHit(qstart=310, qend=624, tstart=430, tend=518, idt=0.7865, strand=1, query='AT_09_1|AT_09_1-1766_EDGE_3202_length_921_cov_47.709:1:2:43940', score=315, probe='1766'),
 miniprotHit(qstart=306, qend=620, tstart=430, tend=518, idt=0.6865, strand=1, query='AT_09_1|AT_09_1-1766_EDGE_3202_length_917_cov_46.9629:1:3:43065', score=302, probe='1766'),
 miniprotHit(qstart=306, qend=620, tstart=430, tend=518, idt=0.6865, strand=1, query='AT_09_1|AT_09_1-1766_EDGE_3204_length_906_cov_45.1093:1:10:40869', score=302, probe='1766'),
 miniprotHit(qstart=306, qend=620, tstart=430, tend=518, idt=0.6865, strand=1, query='AT_09_1|AT_09_1-1766_EDGE_3202_length_886_cov_44.0474:1:4:39026', score=302, probe='1766'),
 miniprotHit(qstart=421, qend=3035, tstart=0, tend=430, idt=0.9184, strand=1, query='AT_18_1|AT_18_1-1766_EDGE_454_length_3201_cov_143.3436:1:1:458843', score=2050, probe='1766'),
 miniprotHit(qstart=407, qend=2974, tstart=0, tend=430, idt=0.9443, strand=1, query='AT_18_1|AT_18_1-1766_EDGE_454_length_3140_cov_133.9248:1:2:420524', score=2123, probe='1766'),
 miniprotHit(qstart=381, qend=2948, tstart=0, tend=430, idt=0.9443, strand=1, query='AT_18_1|AT_18_1-1766_EDGE_454_length_3114_cov_134.9595:1:3:420264', score=2123, probe='1766'),
 miniprotHit(qstart=409, qend=788, tstart=430, tend=518, idt=0.6798, strand=1, query='AT_18_1|SP_04_4-1766_EDGE_1594_length_987_cov_778.8267:1:1:768702', score=350, probe='1766'),
 miniprotHit(qstart=152, qend=1083, tstart=0, tend=280, idt=0.9288, strand=1, query='AT_20_1|AT_20_1-1766_EDGE_1376_length_1322_cov_106.0408:1:1:140186', score=1356, probe='1766'),
 miniprotHit(qstart=148, qend=1051, tstart=9, tend=280, idt=0.9118, strand=1, query='AT_20_1|AT_20_1-1766_EDGE_1376_length_1291_cov_106.0906:1:2:136963', score=1300, probe='1766'),
 miniprotHit(qstart=183, qend=1021, tstart=281, tend=430, idt=0.96, strand=1, query='AT_20_1|BA_18_1-1766_EDGE_1907_length_1190_cov_61.3118:1:2:72961', score=710, probe='1766'),
 miniprotHit(qstart=135, qend=1033, tstart=11, tend=280, idt=0.9259, strand=1, query='AT_20_1|AT_20_1-1766_EDGE_1376_length_1184_cov_122.9527:2:1:145576', score=1301, probe='1766'),
 miniprotHit(qstart=162, qend=1003, tstart=281, tend=430, idt=0.8875, strand=1, query='AT_20_1|BA_18_1-1766_EDGE_1907_length_1172_cov_60.2406:1:4:70602', score=697, probe='1766'),
 miniprotHit(qstart=164, qend=817, tstart=281, tend=415, idt=0.9481, strand=1, query='AT_20_1|EN_19_1-1766_EDGE_1371_length_987_cov_72.3536:1:1:71413', score=670, probe='1766'),
 miniprotHit(qstart=247, qend=635, tstart=430, tend=518, idt=0.6706, strand=1, query='AT_20_1|AT_20_1-1766_EDGE_3365_length_842_cov_527.9394:2:1:444525', score=350, probe='1766'),
 miniprotHit(qstart=247, qend=635, tstart=430, tend=518, idt=0.6618, strand=1, query='AT_20_1|AT_20_1-1766_EDGE_3950_length_782_cov_568.1918:1:1:444326', score=347, probe='1766'),
 miniprotHit(qstart=247, qend=635, tstart=430, tend=518, idt=0.6706, strand=1, query='AT_20_1|B17_002_01-1766_EDGE_621_length_777_cov_571.9356:1:1:444394', score=350, probe='1766'),
 miniprotHit(qstart=216, qend=548, tstart=430, tend=518, idt=0.8861, strand=1, query='AT_20_1|B17_002_01-1766_EDGE_621_length_690_cov_45.5609:1:2:31437', score=376, probe='1766'),
 miniprotHit(qstart=198, qend=512, tstart=430, tend=518, idt=0.6865, strand=1, query='AT_20_1|AT_20_1-1766_EDGE_3365_length_586_cov_27.5137:3:3:16123', score=302, probe='1766'),
 miniprotHit(qstart=407, qend=3060, tstart=0, tend=430, idt=0.9184, strand=1, query='B12_012_1|B12_012_1-1766_EDGE_1142_length_3381_cov_139.614:1:2:472035', score=2075, probe='1766'),
 miniprotHit(qstart=427, qend=1713, tstart=0, tend=280, idt=0.7936, strand=1, query='B12_012_1|K17_23_1-1766_EDGE_375_length_2123_cov_213.0777:1:7:452364', score=1052, probe='1766'),
 miniprotHit(qstart=0, qend=1628, tstart=155, tend=430, idt=0.9336, strand=1, query='B12_012_1|B12_012_1-1766_EDGE_1142_length_1949_cov_140.6788:1:10:274183', score=1343, probe='1766'),
 miniprotHit(qstart=394, qend=736, tstart=430, tend=518, idt=0.7755, strand=1, query='B12_012_1|K22_14_1-1766_EDGE_1088_length_971_cov_81.6437:1:1:79276', score=381, probe='1766'),
 miniprotHit(qstart=253, qend=913, tstart=0, tend=73, idt=0.8649, strand=1, query='B12_012_1|B12_012_1-1766_EDGE_159_length_916_cov_87.2456:1:9:79917', score=337, probe='1766'),
 miniprotHit(qstart=394, qend=709, tstart=430, tend=518, idt=0.764, strand=1, query='B12_012_1|B12_012_1-1766_EDGE_1866_length_902_cov_15.4812:1:1:13964', score=296, probe='1766'),
 miniprotHit(qstart=179, qend=2330, tstart=9, tend=430, idt=0.9051, strand=1, query='B16_001_01|IT_07_1-1766_EDGE_569_length_2394_cov_51.086:1:1:122300', score=2000, probe='1766'),
 miniprotHit(qstart=86, qend=2237, tstart=9, tend=430, idt=0.9051, strand=1, query='B16_001_01|K17_23_1-1766_EDGE_375_length_2301_cov_52.4967:1:1:120795', score=2000, probe='1766'),
 miniprotHit(qstart=179, qend=2143, tstart=9, tend=415, idt=0.9238, strand=1, query='B16_001_01|IT_07_1-1766_EDGE_569_length_2222_cov_47.9752:1:2:106601', score=1970, probe='1766'),
 miniprotHit(qstart=86, qend=2050, tstart=9, tend=415, idt=0.9238, strand=1, query='B16_001_01|K17_23_1-1766_EDGE_375_length_2129_cov_49.364:1:2:105096', score=1970, probe='1766'),
 miniprotHit(qstart=193, qend=1091, tstart=11, tend=280, idt=0.9259, strand=1, query='B16_001_01|SP_02_1-1766_EDGE_235_length_1210_cov_49.7496:1:1:60197', score=1301, probe='1766'),
 miniprotHit(qstart=309, qend=623, tstart=430, tend=518, idt=0.6865, strand=1, query='B16_001_01|B16_001_01-1766_EDGE_1544_length_914_cov_14.977:1:1:13689', score=302, probe='1766'),
 miniprotHit(qstart=52, qend=1310, tstart=80, tend=363, idt=0.9859, strand=1, query='B17_002_01|EN_19_1-1766_EDGE_1371_length_1462_cov_29.7367:1:3:43475', score=1465, probe='1766'),
 miniprotHit(qstart=1, qend=1198, tstart=101, tend=363, idt=0.9734, strand=1, query='B17_002_01|EN_19_1-1766_EDGE_1371_length_1350_cov_28.6089:1:9:38622', score=1337, probe='1766'),
 miniprotHit(qstart=1, qend=1196, tstart=101, tend=363, idt=0.9772, strand=1, query='B17_002_01|EN_19_1-1766_EDGE_1371_length_1348_cov_28.6476:1:10:38617', score=1346, probe='1766'),
 miniprotHit(qstart=198, qend=536, tstart=430, tend=518, idt=0.878, strand=1, query='B17_002_01|B17_002_01-1766_EDGE_621_length_733_cov_31.588:1:2:23154', score=394, probe='1766'),
 miniprotHit(qstart=174, qend=585, tstart=0, tend=107, idt=0.8148, strand=1, query='B17_002_01|B17_002_01-1766_EDGE_431_length_588_cov_18.5629:1:4:10915', score=462, probe='1766'),
 miniprotHit(qstart=198, qend=523, tstart=430, tend=518, idt=0.8014, strand=1, query='B17_002_01|B17_002_01-1766_EDGE_621_length_547_cov_80.9963:1:1:44305', score=358, probe='1766'),
 miniprotHit(qstart=141, qend=2131, tstart=0, tend=415, idt=0.9375, strand=1, query='B17_003|B17_003-1766_EDGE_85_length_2224_cov_56.8817:1:1:126505', score=1993, probe='1766'),
 miniprotHit(qstart=340, qend=678, tstart=430, tend=518, idt=0.878, strand=1, query='B17_003|B17_003-1766_EDGE_998_length_894_cov_53.1857:1:1:47548', score=394, probe='1766'),
 miniprotHit(qstart=153, qend=2281, tstart=11, tend=430, idt=0.9512, strand=1, query='B18_008_01|EN_04_1-1766_EDGE_98_length_2632_cov_66.9814:1:10:176295', score=2091, probe='1766'),
 miniprotHit(qstart=2, qend=2233, tstart=47, tend=430, idt=0.9619, strand=1, query='B18_008_01|EN_19_1-1766_EDGE_1371_length_2584_cov_64.1676:1:10:165809', score=1932, probe='1766'),
 miniprotHit(qstart=138, qend=2091, tstart=9, tend=415, idt=0.9137, strand=1, query='B18_008_01|B18_008_01-1766_EDGE_604_length_2165_cov_73.4998:1:10:159127', score=1950, probe='1766'),
 miniprotHit(qstart=92, qend=2082, tstart=0, tend=415, idt=0.9178, strand=1, query='B18_008_01|B18_008_01-1766_EDGE_604_length_2156_cov_77.9759:1:2:168116', score=1994, probe='1766'),
 miniprotHit(qstart=76, qend=2034, tstart=11, tend=415, idt=0.9181, strand=1, query='B18_008_01|B18_008_01-1766_EDGE_604_length_2108_cov_78.5944:1:7:165677', score=1958, probe='1766'),
 miniprotHit(qstart=302, qend=637, tstart=430, tend=518, idt=0.8873, strand=1, query='B18_008_01|K22_16_1-1766_EDGE_1747_length_1193_cov_46.5876:1:10:55579', score=395, probe='1766'),
 miniprotHit(qstart=302, qend=637, tstart=430, tend=518, idt=0.8873, strand=1, query='B18_008_01|B18_008_01-1766_EDGE_1933_length_785_cov_66.465:1:4:52175', score=395, probe='1766'),
 miniprotHit(qstart=303, qend=617, tstart=430, tend=518, idt=0.7753, strand=1, query='B18_008_01|K22_14_1-1766_EDGE_1088_length_776_cov_36.4936:1:5:28319', score=312, probe='1766'),
 miniprotHit(qstart=303, qend=617, tstart=430, tend=518, idt=0.7865, strand=1, query='B18_008_01|K22_14_1-1766_EDGE_1088_length_762_cov_38.5643:1:3:29386', score=315, probe='1766'),
 miniprotHit(qstart=0, qend=317, tstart=430, tend=518, idt=0.9101, strand=1, query='B18_008_01|K22_14_1-1766_EDGE_1088_length_476_cov_57.9391:1:6:27579', score=393, probe='1766'),
 miniprotHit(qstart=3, qend=2132, tstart=11, tend=430, idt=0.9186, strand=1, query='B19_001|B19_001-1766_EDGE_39_length_2324_cov_17.2332:1:1:40050', score=2012, probe='1766'),
 miniprotHit(qstart=9, qend=2199, tstart=7, tend=430, idt=0.883, strand=1, query='B19_003_01|FRS_35_3-1766_EDGE_143_length_2336_cov_54.0475:1:8:126255', score=1955, probe='1766'),
 miniprotHit(qstart=260, qend=2250, tstart=0, tend=415, idt=0.9375, strand=1, query='B20_007_01|B20_007_01-1766_EDGE_370_length_2339_cov_78.7602:1:2:184220', score=1993, probe='1766'),
 miniprotHit(qstart=399, qend=734, tstart=430, tend=518, idt=0.8873, strand=1, query='B20_007_01|B20_007_01-1766_EDGE_1211_length_1183_cov_64.5089:1:1:76314', score=395, probe='1766'),
 miniprotHit(qstart=436, qend=3089, tstart=0, tend=430, idt=0.9206, strand=1, query='BA_10|BA_10-1766_EDGE_481_length_3425_cov_104.8429:1:5:359087', score=2074, probe='1766'),
 miniprotHit(qstart=436, qend=3082, tstart=0, tend=430, idt=0.9297, strand=1, query='BA_10|BA_10-1766_EDGE_481_length_3415_cov_108.6931:1:4:371187', score=2088, probe='1766'),
 miniprotHit(qstart=374, qend=3029, tstart=0, tend=430, idt=0.9274, strand=1, query='BA_10|BA_10-1766_EDGE_481_length_3362_cov_111.9804:1:2:376478', score=2069, probe='1766'),
 miniprotHit(qstart=272, qend=2927, tstart=0, tend=430, idt=0.9274, strand=1, query='BA_10|BA_10-1766_EDGE_481_length_3260_cov_115.6239:1:1:376934', score=2069, probe='1766'),
 miniprotHit(qstart=348, qend=2373, tstart=0, tend=351, idt=0.9489, strand=1, query='BA_10|K17_23_1-1766_EDGE_375_length_2376_cov_132.2513:1:2:314229', score=1729, probe='1766'),
 miniprotHit(qstart=288, qend=1679, tstart=0, tend=280, idt=0.9431, strand=1, query='BA_10|K15_34_1-1766_EDGE_853_length_2241_cov_248.1709:1:10:556151', score=1380, probe='1766'),
 miniprotHit(qstart=272, qend=1676, tstart=0, tend=280, idt=0.9395, strand=1, query='BA_10|K15_34_1-1766_EDGE_853_length_2239_cov_251.523:1:2:563160', score=1361, probe='1766'),
 miniprotHit(qstart=272, qend=1649, tstart=0, tend=280, idt=0.911, strand=1, query='BA_10|K15_34_1-1766_EDGE_853_length_2212_cov_252.5981:1:8:558747', score=1296, probe='1766'),
 miniprotHit(qstart=272, qend=1556, tstart=0, tend=280, idt=0.7936, strand=1, query='BA_10|BA_10-1766_EDGE_2051_length_2001_cov_126.5142:1:5:253155', score=1052, probe='1766'),
 miniprotHit(qstart=436, qend=1711, tstart=0, tend=280, idt=0.7972, strand=1, query='BA_10|BA_10-1766_EDGE_481_length_1981_cov_114.2256:1:9:226281', score=1071, probe='1766'),
 miniprotHit(qstart=374, qend=1658, tstart=0, tend=280, idt=0.7936, strand=1, query='BA_10|BA_10-1766_EDGE_481_length_1928_cov_120.11:1:7:231572', score=1052, probe='1766'),
 miniprotHit(qstart=348, qend=1632, tstart=0, tend=280, idt=0.7936, strand=1, query='BA_10|K17_23_1-1766_EDGE_375_length_1902_cov_121.6162:1:4:231314', score=1052, probe='1766'),
 miniprotHit(qstart=392, qend=707, tstart=430, tend=518, idt=0.7753, strand=1, query='BA_10|BA_10-1766_EDGE_1870_length_1151_cov_35.0738:2:1:40370', score=310, probe='1766'),
 miniprotHit(qstart=343, qend=676, tstart=430, tend=518, idt=0.8, strand=1, query='BA_10|BA_10-1766_EDGE_1870_length_1046_cov_33.5344:1:1:35077', score=384, probe='1766'),
 miniprotHit(qstart=132, qend=2080, tstart=11, tend=415, idt=0.9084, strand=1, query='BA_14|BA_14-1766_EDGE_2703_length_2256_cov_32.1494:1:2:72529', score=1930, probe='1766'),
 miniprotHit(qstart=132, qend=910, tstart=11, tend=280, idt=0.7741, strand=1, query='BA_14|K15_34_1-1766_EDGE_853_length_1111_cov_35.2574:1:9:39171', score=972, probe='1766'),
 miniprotHit(qstart=132, qend=958, tstart=11, tend=256, idt=0.9187, strand=1, query='BA_14|BA_14-1766_EDGE_2703_length_960_cov_45.3198:1:8:43507', score=1158, probe='1766'),
 miniprotHit(qstart=177, qend=370, tstart=430, tend=495, idt=0.803, strand=1, query='BA_14|K13_16_2-1766_EDGE_974_length_470_cov_7.9319:2:2:3728', score=233, probe='1766'),
 miniprotHit(qstart=405, qend=2972, tstart=0, tend=430, idt=0.9443, strand=1, query='BA_18_1|BA_18_1-1766_EDGE_1905_length_3345_cov_136.0864:1:1:455209', score=2123, probe='1766'),
 miniprotHit(qstart=279, qend=2427, tstart=11, tend=430, idt=0.9093, strand=1, query='BA_18_1|BA_18_1-1766_EDGE_1905_length_2800_cov_146.5007:1:3:410202', score=1994, probe='1766'),
 miniprotHit(qstart=457, qend=2308, tstart=80, tend=430, idt=0.9573, strand=1, query='BA_18_1|BA_18_1-1766_EDGE_1907_length_2681_cov_151.1499:1:4:405233', score=1753, probe='1766'),
 miniprotHit(qstart=211, qend=1573, tstart=0, tend=280, idt=0.9324, strand=1, query='BA_18_1|BA_18_1-1766_EDGE_1908_length_1747_cov_142.6085:1:1:249137', score=1373, probe='1766'),
 miniprotHit(qstart=379, qend=693, tstart=430, tend=518, idt=0.6865, strand=1, query='BA_18_1|BA_18_1-1766_EDGE_3496_length_1056_cov_37.233:1:2:39318', score=302, probe='1766'),
 miniprotHit(qstart=379, qend=693, tstart=430, tend=518, idt=0.764, strand=1, query='BA_18_1|BA_18_1-1766_EDGE_3496_length_1047_cov_38.9045:1:1:40733', score=307, probe='1766'),
 miniprotHit(qstart=374, qend=699, tstart=430, tend=518, idt=0.8014, strand=1, query='BA_18_1|BA_18_1-1766_EDGE_2499_length_882_cov_26.2778:1:1:23177', score=358, probe='1766'),
 miniprotHit(qstart=221, qend=2837, tstart=0, tend=430, idt=0.9397, strand=1, query='BA_20_1|BA_20_1-1766_EDGE_360_length_3055_cov_80.4151:1:10:245668', score=2092, probe='1766'),
 miniprotHit(qstart=205, qend=2782, tstart=0, tend=430, idt=0.9513, strand=1, query='BA_20_1|BA_20_1-1766_EDGE_1870_length_3000_cov_83.0913:1:8:249274', score=2138, probe='1766'),
 miniprotHit(qstart=170, qend=2748, tstart=0, tend=430, idt=0.9466, strand=1, query='BA_20_1|BA_20_1-1766_EDGE_1870_length_2966_cov_84.0421:1:10:249269', score=2132, probe='1766'),
 miniprotHit(qstart=235, qend=549, tstart=430, tend=518, idt=0.764, strand=1, query='BA_20_1|BA_20_1-1766_EDGE_3967_length_785_cov_45.9299:1:3:36055', score=307, probe='1766'),
 miniprotHit(qstart=235, qend=549, tstart=430, tend=518, idt=0.6865, strand=1, query='BA_20_1|BA_20_1-1766_EDGE_3967_length_784_cov_45.4745:1:6:35652', score=302, probe='1766'),
 miniprotHit(qstart=235, qend=549, tstart=430, tend=518, idt=0.764, strand=1, query='BA_20_1|BA_20_1-1766_EDGE_3967_length_784_cov_46.0485:1:1:36102', score=307, probe='1766'),
 miniprotHit(qstart=235, qend=549, tstart=430, tend=518, idt=0.6865, strand=1, query='BA_20_1|K22_14_1-1766_EDGE_1088_length_702_cov_47.7094:1:2:33492', score=302, probe='1766'),
 miniprotHit(qstart=230, qend=555, tstart=430, tend=518, idt=0.8014, strand=1, query='BA_20_1|BA_20_1-1766_EDGE_2788_length_607_cov_33.9802:1:1:20626', score=358, probe='1766'),
 miniprotHit(qstart=179, qend=2853, tstart=0, tend=430, idt=0.9206, strand=1, query='BA_21|BA_21-1766_EDGE_307_length_3173_cov_71.7293:1:2:227597', score=2074, probe='1766'),
 miniprotHit(qstart=98, qend=2246, tstart=11, tend=430, idt=0.9209, strand=1, query='BA_21|BA_21-1766_EDGE_307_length_2566_cov_83.6695:1:3:214696', score=2019, probe='1766'),
 miniprotHit(qstart=196, qend=1038, tstart=281, tend=430, idt=0.9, strand=1, query='BA_21|BA_21-1766_EDGE_307_length_1358_cov_55.5074:1:6:75379', score=705, probe='1766'),
 miniprotHit(qstart=98, qend=876, tstart=11, tend=280, idt=0.7778, strand=1, query='BA_21|K15_34_1-1766_EDGE_853_length_1355_cov_83.7336:1:3:113459', score=1000, probe='1766'),
 miniprotHit(qstart=199, qend=547, tstart=430, tend=518, idt=0.76, strand=1, query='BA_21|K22_14_1-1766_EDGE_1088_length_697_cov_73.8034:1:1:51441', score=379, probe='1766'),
 miniprotHit(qstart=199, qend=547, tstart=430, tend=518, idt=0.76, strand=1, query='BA_21|BA_21-1766_EDGE_1957_length_693_cov_84.7085:1:10:58703', score=379, probe='1766'),
 miniprotHit(qstart=126, qend=441, tstart=430, tend=518, idt=0.764, strand=1, query='BA_21|BA_21-1766_EDGE_2408_length_506_cov_10.2154:1:1:5169', score=296, probe='1766'),

In [17]:
hits

[miniprotHit(qstart=286, qend=2939, tstart=0, tend=430, idt=0.9206, strand=1, query='AT_01_1|AT_01_1-1766_EDGE_1739_length_3329_cov_112.0481:2:1:373008', score=2074, probe='1766'),
 miniprotHit(qstart=317, qend=2972, tstart=0, tend=430, idt=0.9274, strand=1, query='AT_01_1|AT_01_1-1766_EDGE_1739_length_3225_cov_130.5957:1:1:421171', score=2069, probe='1766'),
 miniprotHit(qstart=317, qend=1601, tstart=0, tend=280, idt=0.7936, strand=1, query='AT_01_1|AT_01_1-1766_EDGE_1738_length_1978_cov_120.5905:1:2:238528', score=1052, probe='1766'),
 miniprotHit(qstart=296, qend=611, tstart=430, tend=518, idt=0.764, strand=1, query='AT_01_1|AT_01_1-1766_EDGE_1423_length_975_cov_33.4544:1:1:32618', score=296, probe='1766'),
 miniprotHit(qstart=291, qend=642, tstart=430, tend=518, idt=0.7525, strand=1, query='AT_01_1|AT_01_1-1766_EDGE_2057_length_853_cov_15.2673:1:1:13023', score=378, probe='1766'),
 miniprotHit(qstart=128, qend=2779, tstart=0, tend=430, idt=0.9206, strand=1, query='AT_02_1|AT_02_1-1766_EDGE_1496_length_3099_cov_123.645:1:10:383176', score=2084, probe='1766'),
 miniprotHit(qstart=206, qend=2772, tstart=0, tend=430, idt=0.9206, strand=1, query='AT_02_1|AT_02_1-1766_EDGE_1496_length_3092_cov_126.4301:1:3:390922', score=2077, probe='1766'),
 miniprotHit(qstart=0, qend=2573, tstart=8, tend=430, idt=0.9169, strand=1, query='AT_02_1|AT_02_1-1766_EDGE_1496_length_2893_cov_133.2147:1:5:385390', score=2033, probe='1766'),
 miniprotHit(qstart=183, qend=2328, tstart=11, tend=430, idt=0.9372, strand=1, query='AT_02_1|IT_07_1-1766_EDGE_569_length_2648_cov_141.213:1:3:373932', score=2055, probe='1766'),
 miniprotHit(qstart=179, qend=2327, tstart=11, tend=430, idt=0.9093, strand=1, query='AT_02_1|IT_07_1-1766_EDGE_569_length_2647_cov_136.6162:1:10:361623', score=1994, probe='1766'),
 miniprotHit(qstart=368, qend=1208, tstart=281, tend=430, idt=0.9, strand=1, query='AT_02_1|AT_02_1-1766_EDGE_1496_length_1660_cov_95.7657:2:10:158971', score=705, probe='1766'),
 miniprotHit(qstart=361, qend=675, tstart=430, tend=518, idt=0.7865, strand=1, query='AT_02_1|K22_16_1-1766_EDGE_1747_length_1006_cov_54.0179:1:7:54342', score=315, probe='1766'),
 miniprotHit(qstart=374, qend=694, tstart=430, tend=518, idt=0.9033, strand=1, query='AT_02_1|K22_14_1-1766_EDGE_1088_length_960_cov_49.4208:1:8:47444', score=388, probe='1766'),
 miniprotHit(qstart=375, qend=689, tstart=430, tend=518, idt=0.6865, strand=1, query='AT_02_1|K22_14_1-1766_EDGE_1088_length_953_cov_57.8332:1:2:55115', score=302, probe='1766'),
 miniprotHit(qstart=357, qend=2501, tstart=11, tend=430, idt=0.9667, strand=1, query='AT_09_1|AT_02_1-1766_EDGE_1496_length_2828_cov_97.0636:1:3:274496', score=2071, probe='1766'),
 miniprotHit(qstart=135, qend=1691, tstart=11, tend=363, idt=0.9433, strand=1, query='AT_09_1|AT_02_1-1766_EDGE_1496_length_1934_cov_124.3475:2:1:240488', score=1753, probe='1766'),
 miniprotHit(qstart=358, qend=1199, tstart=281, tend=430, idt=0.9062, strand=1, query='AT_09_1|K17_23_1-1766_EDGE_375_length_1525_cov_63.9233:1:2:97483', score=710, probe='1766'),
 miniprotHit(qstart=330, qend=650, tstart=430, tend=518, idt=0.9033, strand=1, query='AT_09_1|AT_09_1-1766_EDGE_3202_length_947_cov_65.7339:1:1:62250', score=388, probe='1766'),
 miniprotHit(qstart=310, qend=624, tstart=430, tend=518, idt=0.7865, strand=1, query='AT_09_1|AT_09_1-1766_EDGE_3202_length_921_cov_47.709:1:2:43940', score=315, probe='1766'),
 miniprotHit(qstart=306, qend=620, tstart=430, tend=518, idt=0.6865, strand=1, query='AT_09_1|AT_09_1-1766_EDGE_3202_length_917_cov_46.9629:1:3:43065', score=302, probe='1766'),
 miniprotHit(qstart=306, qend=620, tstart=430, tend=518, idt=0.6865, strand=1, query='AT_09_1|AT_09_1-1766_EDGE_3204_length_906_cov_45.1093:1:10:40869', score=302, probe='1766'),
 miniprotHit(qstart=306, qend=620, tstart=430, tend=518, idt=0.6865, strand=1, query='AT_09_1|AT_09_1-1766_EDGE_3202_length_886_cov_44.0474:1:4:39026', score=302, probe='1766'),
 miniprotHit(qstart=421, qend=3035, tstart=0, tend=430, idt=0.9184, strand=1, query='AT_18_1|AT_18_1-1766_EDGE_454_length_3201_cov_143.3436:1:1:458843', score=2050, probe='1766'),
 miniprotHit(qstart=407, qend=2974, tstart=0, tend=430, idt=0.9443, strand=1, query='AT_18_1|AT_18_1-1766_EDGE_454_length_3140_cov_133.9248:1:2:420524', score=2123, probe='1766'),
 miniprotHit(qstart=381, qend=2948, tstart=0, tend=430, idt=0.9443, strand=1, query='AT_18_1|AT_18_1-1766_EDGE_454_length_3114_cov_134.9595:1:3:420264', score=2123, probe='1766'),
 miniprotHit(qstart=409, qend=788, tstart=430, tend=518, idt=0.6798, strand=1, query='AT_18_1|SP_04_4-1766_EDGE_1594_length_987_cov_778.8267:1:1:768702', score=350, probe='1766'),
 miniprotHit(qstart=152, qend=1083, tstart=0, tend=280, idt=0.9288, strand=1, query='AT_20_1|AT_20_1-1766_EDGE_1376_length_1322_cov_106.0408:1:1:140186', score=1356, probe='1766'),
 miniprotHit(qstart=148, qend=1051, tstart=9, tend=280, idt=0.9118, strand=1, query='AT_20_1|AT_20_1-1766_EDGE_1376_length_1291_cov_106.0906:1:2:136963', score=1300, probe='1766'),
 miniprotHit(qstart=183, qend=1021, tstart=281, tend=430, idt=0.96, strand=1, query='AT_20_1|BA_18_1-1766_EDGE_1907_length_1190_cov_61.3118:1:2:72961', score=710, probe='1766'),
 miniprotHit(qstart=135, qend=1033, tstart=11, tend=280, idt=0.9259, strand=1, query='AT_20_1|AT_20_1-1766_EDGE_1376_length_1184_cov_122.9527:2:1:145576', score=1301, probe='1766'),
 miniprotHit(qstart=162, qend=1003, tstart=281, tend=430, idt=0.8875, strand=1, query='AT_20_1|BA_18_1-1766_EDGE_1907_length_1172_cov_60.2406:1:4:70602', score=697, probe='1766'),
 miniprotHit(qstart=164, qend=817, tstart=281, tend=415, idt=0.9481, strand=1, query='AT_20_1|EN_19_1-1766_EDGE_1371_length_987_cov_72.3536:1:1:71413', score=670, probe='1766'),
 miniprotHit(qstart=247, qend=635, tstart=430, tend=518, idt=0.6706, strand=1, query='AT_20_1|AT_20_1-1766_EDGE_3365_length_842_cov_527.9394:2:1:444525', score=350, probe='1766'),
 miniprotHit(qstart=247, qend=635, tstart=430, tend=518, idt=0.6618, strand=1, query='AT_20_1|AT_20_1-1766_EDGE_3950_length_782_cov_568.1918:1:1:444326', score=347, probe='1766'),
 miniprotHit(qstart=247, qend=635, tstart=430, tend=518, idt=0.6706, strand=1, query='AT_20_1|B17_002_01-1766_EDGE_621_length_777_cov_571.9356:1:1:444394', score=350, probe='1766'),
 miniprotHit(qstart=216, qend=548, tstart=430, tend=518, idt=0.8861, strand=1, query='AT_20_1|B17_002_01-1766_EDGE_621_length_690_cov_45.5609:1:2:31437', score=376, probe='1766'),
 miniprotHit(qstart=198, qend=512, tstart=430, tend=518, idt=0.6865, strand=1, query='AT_20_1|AT_20_1-1766_EDGE_3365_length_586_cov_27.5137:3:3:16123', score=302, probe='1766'),
 miniprotHit(qstart=407, qend=3060, tstart=0, tend=430, idt=0.9184, strand=1, query='B12_012_1|B12_012_1-1766_EDGE_1142_length_3381_cov_139.614:1:2:472035', score=2075, probe='1766'),
 miniprotHit(qstart=427, qend=1713, tstart=0, tend=280, idt=0.7936, strand=1, query='B12_012_1|K17_23_1-1766_EDGE_375_length_2123_cov_213.0777:1:7:452364', score=1052, probe='1766'),
 miniprotHit(qstart=0, qend=1628, tstart=155, tend=430, idt=0.9336, strand=1, query='B12_012_1|B12_012_1-1766_EDGE_1142_length_1949_cov_140.6788:1:10:274183', score=1343, probe='1766'),
 miniprotHit(qstart=394, qend=736, tstart=430, tend=518, idt=0.7755, strand=1, query='B12_012_1|K22_14_1-1766_EDGE_1088_length_971_cov_81.6437:1:1:79276', score=381, probe='1766'),
 miniprotHit(qstart=253, qend=913, tstart=0, tend=73, idt=0.8649, strand=1, query='B12_012_1|B12_012_1-1766_EDGE_159_length_916_cov_87.2456:1:9:79917', score=337, probe='1766'),
 miniprotHit(qstart=394, qend=709, tstart=430, tend=518, idt=0.764, strand=1, query='B12_012_1|B12_012_1-1766_EDGE_1866_length_902_cov_15.4812:1:1:13964', score=296, probe='1766'),
 miniprotHit(qstart=179, qend=2330, tstart=9, tend=430, idt=0.9051, strand=1, query='B16_001_01|IT_07_1-1766_EDGE_569_length_2394_cov_51.086:1:1:122300', score=2000, probe='1766'),
 miniprotHit(qstart=86, qend=2237, tstart=9, tend=430, idt=0.9051, strand=1, query='B16_001_01|K17_23_1-1766_EDGE_375_length_2301_cov_52.4967:1:1:120795', score=2000, probe='1766'),
 miniprotHit(qstart=179, qend=2143, tstart=9, tend=415, idt=0.9238, strand=1, query='B16_001_01|IT_07_1-1766_EDGE_569_length_2222_cov_47.9752:1:2:106601', score=1970, probe='1766'),
 miniprotHit(qstart=86, qend=2050, tstart=9, tend=415, idt=0.9238, strand=1, query='B16_001_01|K17_23_1-1766_EDGE_375_length_2129_cov_49.364:1:2:105096', score=1970, probe='1766'),
 miniprotHit(qstart=193, qend=1091, tstart=11, tend=280, idt=0.9259, strand=1, query='B16_001_01|SP_02_1-1766_EDGE_235_length_1210_cov_49.7496:1:1:60197', score=1301, probe='1766'),
 miniprotHit(qstart=309, qend=623, tstart=430, tend=518, idt=0.6865, strand=1, query='B16_001_01|B16_001_01-1766_EDGE_1544_length_914_cov_14.977:1:1:13689', score=302, probe='1766'),
 miniprotHit(qstart=52, qend=1310, tstart=80, tend=363, idt=0.9859, strand=1, query='B17_002_01|EN_19_1-1766_EDGE_1371_length_1462_cov_29.7367:1:3:43475', score=1465, probe='1766'),
 miniprotHit(qstart=1, qend=1198, tstart=101, tend=363, idt=0.9734, strand=1, query='B17_002_01|EN_19_1-1766_EDGE_1371_length_1350_cov_28.6089:1:9:38622', score=1337, probe='1766'),
 miniprotHit(qstart=1, qend=1196, tstart=101, tend=363, idt=0.9772, strand=1, query='B17_002_01|EN_19_1-1766_EDGE_1371_length_1348_cov_28.6476:1:10:38617', score=1346, probe='1766'),
 miniprotHit(qstart=198, qend=536, tstart=430, tend=518, idt=0.878, strand=1, query='B17_002_01|B17_002_01-1766_EDGE_621_length_733_cov_31.588:1:2:23154', score=394, probe='1766'),
 miniprotHit(qstart=174, qend=585, tstart=0, tend=107, idt=0.8148, strand=1, query='B17_002_01|B17_002_01-1766_EDGE_431_length_588_cov_18.5629:1:4:10915', score=462, probe='1766'),
 miniprotHit(qstart=198, qend=523, tstart=430, tend=518, idt=0.8014, strand=1, query='B17_002_01|B17_002_01-1766_EDGE_621_length_547_cov_80.9963:1:1:44305', score=358, probe='1766'),
 miniprotHit(qstart=141, qend=2131, tstart=0, tend=415, idt=0.9375, strand=1, query='B17_003|B17_003-1766_EDGE_85_length_2224_cov_56.8817:1:1:126505', score=1993, probe='1766'),
 miniprotHit(qstart=340, qend=678, tstart=430, tend=518, idt=0.878, strand=1, query='B17_003|B17_003-1766_EDGE_998_length_894_cov_53.1857:1:1:47548', score=394, probe='1766'),
 miniprotHit(qstart=153, qend=2281, tstart=11, tend=430, idt=0.9512, strand=1, query='B18_008_01|EN_04_1-1766_EDGE_98_length_2632_cov_66.9814:1:10:176295', score=2091, probe='1766'),
 miniprotHit(qstart=2, qend=2233, tstart=47, tend=430, idt=0.9619, strand=1, query='B18_008_01|EN_19_1-1766_EDGE_1371_length_2584_cov_64.1676:1:10:165809', score=1932, probe='1766'),
 miniprotHit(qstart=138, qend=2091, tstart=9, tend=415, idt=0.9137, strand=1, query='B18_008_01|B18_008_01-1766_EDGE_604_length_2165_cov_73.4998:1:10:159127', score=1950, probe='1766'),
 miniprotHit(qstart=92, qend=2082, tstart=0, tend=415, idt=0.9178, strand=1, query='B18_008_01|B18_008_01-1766_EDGE_604_length_2156_cov_77.9759:1:2:168116', score=1994, probe='1766'),
 miniprotHit(qstart=76, qend=2034, tstart=11, tend=415, idt=0.9181, strand=1, query='B18_008_01|B18_008_01-1766_EDGE_604_length_2108_cov_78.5944:1:7:165677', score=1958, probe='1766'),
 miniprotHit(qstart=302, qend=637, tstart=430, tend=518, idt=0.8873, strand=1, query='B18_008_01|K22_16_1-1766_EDGE_1747_length_1193_cov_46.5876:1:10:55579', score=395, probe='1766'),
 miniprotHit(qstart=302, qend=637, tstart=430, tend=518, idt=0.8873, strand=1, query='B18_008_01|B18_008_01-1766_EDGE_1933_length_785_cov_66.465:1:4:52175', score=395, probe='1766'),
 miniprotHit(qstart=303, qend=617, tstart=430, tend=518, idt=0.7753, strand=1, query='B18_008_01|K22_14_1-1766_EDGE_1088_length_776_cov_36.4936:1:5:28319', score=312, probe='1766'),
 miniprotHit(qstart=303, qend=617, tstart=430, tend=518, idt=0.7865, strand=1, query='B18_008_01|K22_14_1-1766_EDGE_1088_length_762_cov_38.5643:1:3:29386', score=315, probe='1766'),
 miniprotHit(qstart=0, qend=317, tstart=430, tend=518, idt=0.9101, strand=1, query='B18_008_01|K22_14_1-1766_EDGE_1088_length_476_cov_57.9391:1:6:27579', score=393, probe='1766'),
 miniprotHit(qstart=3, qend=2132, tstart=11, tend=430, idt=0.9186, strand=1, query='B19_001|B19_001-1766_EDGE_39_length_2324_cov_17.2332:1:1:40050', score=2012, probe='1766'),
 miniprotHit(qstart=9, qend=2199, tstart=7, tend=430, idt=0.883, strand=1, query='B19_003_01|FRS_35_3-1766_EDGE_143_length_2336_cov_54.0475:1:8:126255', score=1955, probe='1766'),
 miniprotHit(qstart=260, qend=2250, tstart=0, tend=415, idt=0.9375, strand=1, query='B20_007_01|B20_007_01-1766_EDGE_370_length_2339_cov_78.7602:1:2:184220', score=1993, probe='1766'),
 miniprotHit(qstart=399, qend=734, tstart=430, tend=518, idt=0.8873, strand=1, query='B20_007_01|B20_007_01-1766_EDGE_1211_length_1183_cov_64.5089:1:1:76314', score=395, probe='1766'),
 miniprotHit(qstart=436, qend=3089, tstart=0, tend=430, idt=0.9206, strand=1, query='BA_10|BA_10-1766_EDGE_481_length_3425_cov_104.8429:1:5:359087', score=2074, probe='1766'),
 miniprotHit(qstart=436, qend=3082, tstart=0, tend=430, idt=0.9297, strand=1, query='BA_10|BA_10-1766_EDGE_481_length_3415_cov_108.6931:1:4:371187', score=2088, probe='1766'),
 miniprotHit(qstart=374, qend=3029, tstart=0, tend=430, idt=0.9274, strand=1, query='BA_10|BA_10-1766_EDGE_481_length_3362_cov_111.9804:1:2:376478', score=2069, probe='1766'),
 miniprotHit(qstart=272, qend=2927, tstart=0, tend=430, idt=0.9274, strand=1, query='BA_10|BA_10-1766_EDGE_481_length_3260_cov_115.6239:1:1:376934', score=2069, probe='1766'),
 miniprotHit(qstart=348, qend=2373, tstart=0, tend=351, idt=0.9489, strand=1, query='BA_10|K17_23_1-1766_EDGE_375_length_2376_cov_132.2513:1:2:314229', score=1729, probe='1766'),
 miniprotHit(qstart=288, qend=1679, tstart=0, tend=280, idt=0.9431, strand=1, query='BA_10|K15_34_1-1766_EDGE_853_length_2241_cov_248.1709:1:10:556151', score=1380, probe='1766'),
 miniprotHit(qstart=272, qend=1676, tstart=0, tend=280, idt=0.9395, strand=1, query='BA_10|K15_34_1-1766_EDGE_853_length_2239_cov_251.523:1:2:563160', score=1361, probe='1766'),
 miniprotHit(qstart=272, qend=1649, tstart=0, tend=280, idt=0.911, strand=1, query='BA_10|K15_34_1-1766_EDGE_853_length_2212_cov_252.5981:1:8:558747', score=1296, probe='1766'),
 miniprotHit(qstart=272, qend=1556, tstart=0, tend=280, idt=0.7936, strand=1, query='BA_10|BA_10-1766_EDGE_2051_length_2001_cov_126.5142:1:5:253155', score=1052, probe='1766'),
 miniprotHit(qstart=436, qend=1711, tstart=0, tend=280, idt=0.7972, strand=1, query='BA_10|BA_10-1766_EDGE_481_length_1981_cov_114.2256:1:9:226281', score=1071, probe='1766'),
 miniprotHit(qstart=374, qend=1658, tstart=0, tend=280, idt=0.7936, strand=1, query='BA_10|BA_10-1766_EDGE_481_length_1928_cov_120.11:1:7:231572', score=1052, probe='1766'),
 miniprotHit(qstart=348, qend=1632, tstart=0, tend=280, idt=0.7936, strand=1, query='BA_10|K17_23_1-1766_EDGE_375_length_1902_cov_121.6162:1:4:231314', score=1052, probe='1766'),
 miniprotHit(qstart=392, qend=707, tstart=430, tend=518, idt=0.7753, strand=1, query='BA_10|BA_10-1766_EDGE_1870_length_1151_cov_35.0738:2:1:40370', score=310, probe='1766'),
 miniprotHit(qstart=343, qend=676, tstart=430, tend=518, idt=0.8, strand=1, query='BA_10|BA_10-1766_EDGE_1870_length_1046_cov_33.5344:1:1:35077', score=384, probe='1766'),
 miniprotHit(qstart=132, qend=2080, tstart=11, tend=415, idt=0.9084, strand=1, query='BA_14|BA_14-1766_EDGE_2703_length_2256_cov_32.1494:1:2:72529', score=1930, probe='1766'),
 miniprotHit(qstart=132, qend=910, tstart=11, tend=280, idt=0.7741, strand=1, query='BA_14|K15_34_1-1766_EDGE_853_length_1111_cov_35.2574:1:9:39171', score=972, probe='1766'),
 miniprotHit(qstart=132, qend=958, tstart=11, tend=256, idt=0.9187, strand=1, query='BA_14|BA_14-1766_EDGE_2703_length_960_cov_45.3198:1:8:43507', score=1158, probe='1766'),
 miniprotHit(qstart=177, qend=370, tstart=430, tend=495, idt=0.803, strand=1, query='BA_14|K13_16_2-1766_EDGE_974_length_470_cov_7.9319:2:2:3728', score=233, probe='1766'),
 miniprotHit(qstart=405, qend=2972, tstart=0, tend=430, idt=0.9443, strand=1, query='BA_18_1|BA_18_1-1766_EDGE_1905_length_3345_cov_136.0864:1:1:455209', score=2123, probe='1766'),
 miniprotHit(qstart=279, qend=2427, tstart=11, tend=430, idt=0.9093, strand=1, query='BA_18_1|BA_18_1-1766_EDGE_1905_length_2800_cov_146.5007:1:3:410202', score=1994, probe='1766'),
 miniprotHit(qstart=457, qend=2308, tstart=80, tend=430, idt=0.9573, strand=1, query='BA_18_1|BA_18_1-1766_EDGE_1907_length_2681_cov_151.1499:1:4:405233', score=1753, probe='1766'),
 miniprotHit(qstart=211, qend=1573, tstart=0, tend=280, idt=0.9324, strand=1, query='BA_18_1|BA_18_1-1766_EDGE_1908_length_1747_cov_142.6085:1:1:249137', score=1373, probe='1766'),
 miniprotHit(qstart=379, qend=693, tstart=430, tend=518, idt=0.6865, strand=1, query='BA_18_1|BA_18_1-1766_EDGE_3496_length_1056_cov_37.233:1:2:39318', score=302, probe='1766'),
 miniprotHit(qstart=379, qend=693, tstart=430, tend=518, idt=0.764, strand=1, query='BA_18_1|BA_18_1-1766_EDGE_3496_length_1047_cov_38.9045:1:1:40733', score=307, probe='1766'),
 miniprotHit(qstart=374, qend=699, tstart=430, tend=518, idt=0.8014, strand=1, query='BA_18_1|BA_18_1-1766_EDGE_2499_length_882_cov_26.2778:1:1:23177', score=358, probe='1766'),
 miniprotHit(qstart=221, qend=2837, tstart=0, tend=430, idt=0.9397, strand=1, query='BA_20_1|BA_20_1-1766_EDGE_360_length_3055_cov_80.4151:1:10:245668', score=2092, probe='1766'),
 miniprotHit(qstart=205, qend=2782, tstart=0, tend=430, idt=0.9513, strand=1, query='BA_20_1|BA_20_1-1766_EDGE_1870_length_3000_cov_83.0913:1:8:249274', score=2138, probe='1766'),
 miniprotHit(qstart=170, qend=2748, tstart=0, tend=430, idt=0.9466, strand=1, query='BA_20_1|BA_20_1-1766_EDGE_1870_length_2966_cov_84.0421:1:10:249269', score=2132, probe='1766'),
 miniprotHit(qstart=235, qend=549, tstart=430, tend=518, idt=0.764, strand=1, query='BA_20_1|BA_20_1-1766_EDGE_3967_length_785_cov_45.9299:1:3:36055', score=307, probe='1766'),
 miniprotHit(qstart=235, qend=549, tstart=430, tend=518, idt=0.6865, strand=1, query='BA_20_1|BA_20_1-1766_EDGE_3967_length_784_cov_45.4745:1:6:35652', score=302, probe='1766'),
 miniprotHit(qstart=235, qend=549, tstart=430, tend=518, idt=0.764, strand=1, query='BA_20_1|BA_20_1-1766_EDGE_3967_length_784_cov_46.0485:1:1:36102', score=307, probe='1766'),
 miniprotHit(qstart=235, qend=549, tstart=430, tend=518, idt=0.6865, strand=1, query='BA_20_1|K22_14_1-1766_EDGE_1088_length_702_cov_47.7094:1:2:33492', score=302, probe='1766'),
 miniprotHit(qstart=230, qend=555, tstart=430, tend=518, idt=0.8014, strand=1, query='BA_20_1|BA_20_1-1766_EDGE_2788_length_607_cov_33.9802:1:1:20626', score=358, probe='1766'),
 miniprotHit(qstart=179, qend=2853, tstart=0, tend=430, idt=0.9206, strand=1, query='BA_21|BA_21-1766_EDGE_307_length_3173_cov_71.7293:1:2:227597', score=2074, probe='1766'),
 miniprotHit(qstart=98, qend=2246, tstart=11, tend=430, idt=0.9209, strand=1, query='BA_21|BA_21-1766_EDGE_307_length_2566_cov_83.6695:1:3:214696', score=2019, probe='1766'),
 miniprotHit(qstart=196, qend=1038, tstart=281, tend=430, idt=0.9, strand=1, query='BA_21|BA_21-1766_EDGE_307_length_1358_cov_55.5074:1:6:75379', score=705, probe='1766'),
 miniprotHit(qstart=98, qend=876, tstart=11, tend=280, idt=0.7778, strand=1, query='BA_21|K15_34_1-1766_EDGE_853_length_1355_cov_83.7336:1:3:113459', score=1000, probe='1766'),
 miniprotHit(qstart=199, qend=547, tstart=430, tend=518, idt=0.76, strand=1, query='BA_21|K22_14_1-1766_EDGE_1088_length_697_cov_73.8034:1:1:51441', score=379, probe='1766'),
 miniprotHit(qstart=199, qend=547, tstart=430, tend=518, idt=0.76, strand=1, query='BA_21|BA_21-1766_EDGE_1957_length_693_cov_84.7085:1:10:58703', score=379, probe='1766'),
 miniprotHit(qstart=126, qend=441, tstart=430, tend=518, idt=0.764, strand=1, query='BA_21|BA_21-1766_EDGE_2408_length_506_cov_10.2154:1:1:5169', score=296, probe='1766'),